spring:

  datasource:
    url: jdbc:postgresql://localhost:5435/intervention_db
    username: intervention_user
    password: intervention_password


  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false


  flyway:
    enabled: true
    baseline-on-migrate: true